name: book_my_hall
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.4
  image: ^3.0.2
  http: ^0.13.1
  network_image_to_byte: ^0.0.1
  screenshot: ^0.3.0
  flutter_colorpicker: ^0.4.0
  google_fonts: ^2.0.0
  share: ^2.0.1
  image_gallery_saver: ^1.6.8
  flutter_datetime_picker: ^1.5.0
  fluttertoast: ^7.0.2
  # http: 0.12.0+2 
  # network_image_to_byte: ^0.0.1
  # screenshot: ^0.3.0
  # flutter_colorpicker: ^0.4.0
  # google_fonts: 1.1.2
  # esys_flutter_share: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cached_network_image: ^3.0.0
  intl_phone_field: ^2.0.0
  # url_launcher: ^6.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  flutter_admin_scaffold: ^0.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Acme
  #     fonts:
  #       - asset: fonts/Acme-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  #   - family: Acme
  #     fonts:
  #       - asset: fonts/Acme-Regular.ttf
    # - family: Faustina
    #   fonts:
    #     - asset: fonts/Faustina-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
